const CONFIG_RESPONSE_ITEM_LIMIT = 10
const CONFIG_API_ROUTE = '/api'
const CONFIG_ENABLE_FRONTEND = true

module.exports = {
  CONFIG_RESPONSE_ITEM_LIMIT,
  CONFIG_API_ROUTE,
  CONFIG_ENABLE_FRONTEND,
}
